# frozen_string_literal: true

require_relative 'api_call_test'
require_relative 'read_locales'

desc 'Runs example translation'
task :translate do
  ApiCallTest.chatgpt_request('Innenbandriss')
end

desc 'Demos loading of locales for testing'
task :read do
  ReadLocales.read_locale('locales/it.yml')
end
